server:
  port: 8010

spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 101.35.246.213:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public



